# ETL of secondary datasets

# "Volcano Eruptions"

In [1]:
import numpy as np
import pandas as pd

In [2]:
volc = pd.read_csv('Datasets\Input\eruptions.csv', sep=',')

In [3]:
volc

,volcano_number,volcano_name,eruption_number,eruption_category,area_of_activity,vei,start_year,start_month,start_day,evidence_method_dating,end_year,end_month,end_day,latitude,longitude
0,266030,Soputan,22354,Confirmed Eruption,NaN,NaN,2020.0,3.0,23.0,Historical Observations,2020.0,4.0,2.0,1.112,124.737
1,343100,San Miguel,22355,Confirmed Eruption,NaN,NaN,2020.0,2.0,22.0,Historical Observations,2020.0,2.0,22.0,13.434,-88.269
2,233020,"Fournaise, Piton de la",22343,Confirmed Eruption,NaN,NaN,2020.0,2.0,10.0,Historical Observations,2020.0,4.0,6.0,-21.244,55.708
3,345020,Rincon de la Vieja,22346,Confirmed Eruption,NaN,NaN,2020.0,1.0,31.0,Historical Observations,2020.0,4.0,17.0,10.830,-85.324
4,353010,Fernandina,22347,Confirmed Eruption,NaN,NaN,2020.0,1.0,12.0,Historical Observations,2020.0,1.0,12.0,-0.370,-91.550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11173,324020,Craters of the Moon,21101,Confirmed Eruption,Sunset cone,0.0,-10060.0,NaN,NaN,Radiocarbon (uncorrected),NaN,NaN,NaN,43.420,-113.500
11174,222161,Igwisi Hills,22141,Confirmed Eruption,NE Volcano,1.0,-10450.0,NaN,NaN,Surface Exposure,NaN,NaN,NaN,-4.889,31.933
11175,357121,Quetrupillan,22351,Confirmed Eruption,NaN,3.0,-10658.0,NaN,NaN,Radiocarbon (corrected),NaN,NaN,NaN,-39.496,-71.722
11176,357121,Quetrupillan,22352,Confirmed Eruption,NaN,3.0,-11345.0,NaN,NaN,Radiocarbon (corrected),NaN,NaN,NaN,-39.496,-71.722
11177,390090,Saunders,21099,Confirmed Eruption,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-57.800,-26.483

In [18]:
volc['eruption_category'].value_counts()

Confirmed Eruption      9900
Uncertain Eruption      1112
Discredited Eruption     166
Name: eruption_category, dtype: int64

In [19]:
volc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11178 entries, 0 to 11177
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   volcano_number          11178 non-null  int64
 1   volcano_name            11178 non-null  object
 2   eruption_number         11178 non-null  int64
 3   eruption_category       11178 non-null  object
 4   area_of_activity        4694 non-null   object
 5   vei                     8272 non-null   float64
 6   start_year              11177 non-null  float64
 7   start_month             10985 non-null  float64
 8   start_day               10982 non-null  float64
 9   evidence_method_dating  9898 non-null   object
 10  end_year                4332 non-null   float64
 11  end_month               4329 non-null   float64
 12  end_day                 4326 non-null   float64
 13  latitude                11178 non-null  float64
 14  longitude               11178 non-null  float64
dtypes: float64(9), int64(2), object(4)
memory usage: 1.3+ MB

In [24]:
# We set datetime properties for a new column 'Start Date': 

volc.rename(columns={'start_year' : 'Year',
                   'start_month' : 'Month',
                   'start_day' : 'Day'}, inplace=True)


volc ['Start Date'] = pd.to_datetime (volc [["Year", "Month", "Day"]],  errors = 'coerce')

In [27]:
# And for 'End Date': 

volc = volc.drop (['Year', 'Month', 'Day'], axis=1)

volc.rename(columns={'end_year' : 'Year',
                   'end_month' : 'Month',
                   'end_day' : 'Day'}, inplace=True)


volc ['End Date'] = pd.to_datetime (volc [["Year", "Month", "Day"]],  errors = 'coerce')

In [29]:
volc = volc.drop (['Year', 'Month', 'Day'], axis=1)

In [31]:
volc.columns

Index(['volcano_number', 'volcano_name', 'eruption_number',
       'eruption_category', 'area_of_activity', 'vei',
       'evidence_method_dating', 'latitude', 'longitude', 'Start Date',
       'End Date'],
      dtype='object')

In [33]:
# Rearrange columns order:

volc = volc [['volcano_number', 'volcano_name', 'eruption_number',
       'eruption_category', 'Start Date',
       'End Date', 'area_of_activity', 'vei',
       'evidence_method_dating', 'latitude', 'longitude']]

In [35]:
# Final view of finished dataframe

volc

,volcano_number,volcano_name,eruption_number,eruption_category,Start Date,End Date,area_of_activity,vei,evidence_method_dating,latitude,longitude
0,266030,Soputan,22354,Confirmed Eruption,2020-03-23,2020-04-02,NaN,NaN,Historical Observations,1.112,124.737
1,343100,San Miguel,22355,Confirmed Eruption,2020-02-22,2020-02-22,NaN,NaN,Historical Observations,13.434,-88.269
2,233020,"Fournaise, Piton de la",22343,Confirmed Eruption,2020-02-10,2020-04-06,NaN,NaN,Historical Observations,-21.244,55.708
3,345020,Rincon de la Vieja,22346,Confirmed Eruption,2020-01-31,2020-04-17,NaN,NaN,Historical Observations,10.830,-85.324
4,353010,Fernandina,22347,Confirmed Eruption,2020-01-12,2020-01-12,NaN,NaN,Historical Observations,-0.370,-91.550
...,...,...,...,...,...,...,...,...,...,...,...
11173,324020,Craters of the Moon,21101,Confirmed Eruption,NaT,NaT,Sunset cone,0.0,Radiocarbon (uncorrected),43.420,-113.500
11174,222161,Igwisi Hills,22141,Confirmed Eruption,NaT,NaT,NE Volcano,1.0,Surface Exposure,-4.889,31.933
11175,357121,Quetrupillan,22351,Confirmed Eruption,NaT,NaT,NaN,3.0,Radiocarbon (corrected),-39.496,-71.722
11176,357121,Quetrupillan,22352,Confirmed Eruption,NaT,NaT,NaN,3.0,Radiocarbon (corrected),-39.496,-71.722
11177,390090,Saunders,21099,Confirmed Eruption,NaT,NaT,NaN,0.0,NaN,-57.800,-26.483

In [ ]:
volc.to_csv ('Datasets\Output\Volcano-Database.csv')